//
//  MessageContent.swift
//  ChatSDK
//
//  Created by Yurii Zhuk on 06.05.2026.
//

import Foundation


/// Represents message content received from the server.
///
/// A message may contain text, attachments, interactive elements (keyboard),
/// or a combination of these.
///
/// Some cases (e.g. keyboard, system events) are server-driven and are not
/// available when sending messages from the client.
public enum MessageContent: Hashable, Codable  {

    /// Plain text message.
    case text(Text)

    /// Message containing only attachments.
    case attachments(Attachments)

    /// Message containing only an interactive keyboard.
    ///
    /// Typically used for bot-driven UI (quick replies, menus).
    case keyboardOnly(KeyboardOnly)

    /// Message with combined content.
    ///
    /// Supports:
    /// - text + attachments
    /// - text + keyboard
    /// - attachments + keyboard
    /// - text + attachments + keyboard
    case composite(Composite)

    /// Contact information shared in a message.
    case contact(Contact)

    /// Geographic location shared in a message.
    case location(Location)

    /// System message generated by backend or client logic.
    ///
    /// Examples:
    /// - user joined/left
    /// - status updates
//    case system(System)

    /// Plain text payload.
    public struct Text: Hashable, Codable {
        public let text: String
        public init(text: String) { self.text = text }
    }

    /// Attachments payload.
    public struct Attachments: Hashable, Codable {
        public let attachments: [MessageAttachment]
    }

    /// Keyboard-only payload.
    public struct KeyboardOnly: Hashable, Codable {
        public let keyboard: ChatKeyboard
    }

    /// Combined message payload.
    public struct Composite: Hashable, Codable {

        /// Optional text content.
        public let text: String?

        /// Attachments included in the message.
        public let attachments: [MessageAttachment]

        /// Optional interactive keyboard.
        ///
        /// Usually provided by the server.
        public let keyboard: ChatKeyboard?
    }

    /// Contact payload.
    public struct Contact: Hashable, Codable {
        public let name: String
        public let phone: String?
        public let email: String?
        public init(name: String, phone: String? = nil, email: String? = nil) {
            self.name = name
            self.phone = phone
            self.email = email
        }
    }

    /// Location payload.
    public struct Location: Hashable, Codable {
        public let name: String
        public let address: String
        public let latitude: Double
        public let longitude: Double
        public init(
            name: String,
            address: String,
            latitude: Double,
            longitude: Double
        ) {
            self.name = name
            self.address = address
            self.latitude = latitude
            self.longitude = longitude
        }
    }

//    /// System payload.
//    public struct System: Hashable, Codable {
//
//        /// System event type (backend-defined).
//        public let type: String
//
//        /// Human-readable description.
//        public let text: String
//    }
}


/// Represents message content that can be sent from the client.
///
/// This is a restricted subset of `MessageContent`.
/// The server may transform or enrich the message after it is sent.
public enum SendContent {

    /// Plain text message.
    case text(Text)

    /// Contact sharing message.
    case contact(Contact)

    /// Location sharing message.
    case location(Location)
    
    /// Message containing only attachments.
    case attachments(Attachments)

    /// Message with combined content (text + attachments).
    case composite(Composite)


    public struct Text {
        public let text: String
        public init(text: String) { self.text = text }
    }
    

    public struct Attachments {
        public let attachments: [MessageAttachment]
        public init(attachments: [MessageAttachment]) {
            self.attachments = attachments
        }
    }
    

    public struct Contact {
        public let name: String
        public let phone: String?
        public let email: String?
        public init(name: String, phone: String? = nil, email: String? = nil) {
            self.name = name
            self.phone = phone
            self.email = email
        }
    }
    

    public struct Location {
        public let name: String
        public let address: String
        public let latitude: Double
        public let longitude: Double
        public init(
            name: String,
            address: String,
            latitude: Double,
            longitude: Double
        ) {
            self.name = name
            self.address = address
            self.latitude = latitude
            self.longitude = longitude
        }
    }
    

    public struct Composite {
        public let text: String
        public let attachments: [MessageAttachment]
        public init(text: String, attachments: [MessageAttachment] = []) {
            self.text = text
            self.attachments = attachments
        }
    }
}


/// Convenience factory methods for building `SendContent`.
///
/// These helpers provide a clean and concise API, hiding internal models
/// and improving readability at call sites.
public extension SendContent {

    /// Creates a plain text message.
    static func text(_ value: String) -> SendContent {
        .text(.init(text: value))
    }

    /// Creates a message containing only attachments.
    static func attachments(_ items: [MessageAttachment]) -> SendContent {
        .attachments(.init(attachments: items))
    }

    /// Creates a message with text and optional attachments.
    static func composite(
        text: String,
        attachments: [MessageAttachment] = []
    ) -> SendContent {
        .composite(.init(text: text, attachments: attachments))
    }

    /// Creates a contact sharing message.
    static func contact(
        name: String,
        phone: String? = nil,
        email: String? = nil
    ) -> SendContent {
        .contact(.init(name: name, phone: phone, email: email))
    }

    /// Creates a location sharing message.
    static func location(
        name: String,
        address: String,
        latitude: Double,
        longitude: Double
    ) -> SendContent {
        .location(.init(
            name: name,
            address: address,
            latitude: latitude,
            longitude: longitude
        ))
    }
}
