//
//  MessageReply.swift
//  ChatSDK
//
//  Created by Yurii Zhuk on 01.09.2026.
//

import Foundation


/// Quoted message this message replies to, as returned by the server.
public struct MessageReply: Hashable, Codable {

    /// Identifier of the quoted message.
    public let messageId: String

    /// Sender of the quoted message.
    public let from: Participant

    /// Creation timestamp of the quoted message.
    public let createdAt: Date

    /// Whether the quoted message was deleted.
    ///
    /// `content` still reflects the original message type, but attachment
    /// details (mime type, file name, address, etc.) are no longer available.
    public let isDeleted: Bool

    /// Content of the quoted message.
    public let content: MessageReplyContent
}


/// Content of a quoted (`reply_to`) message.
public enum MessageReplyContent: Hashable, Codable {

    /// Plain text message.
    case text(String?)

    /// Image message.
    case image(
        caption: String?,
        mimeType: String?
    )

    /// Document message.
    case document(
        name: String?,
        mimeType: String?,
        caption: String?
    )

    /// Geographic location message.
    case location(
        name: String?,
        address: String?
    )

    /// Contact information message.
    case contact(
        displayValue: String?
    )

    /// System message generated by backend or client logic.
    case system(String)

    /// Interactive keyboard message.
    case interactive(String)

    /// Forward-compat fallback for reply types the SDK doesn't model yet.
    case unsupported(type: String, text: String?)
}
