//
//  MessageContent.swift
//  ChatSDK
//
//  Created by Yurii Zhuk on 06.05.2026.
//

import Foundation


/// Represents message content received from the server.
///
/// A message may contain text, attachments, interactive elements (keyboard),
/// or a combination of these.
///
/// Some cases (e.g. keyboard, system events) are server-driven and are not
/// available when sending messages from the client.
public enum MessageContent: Hashable, Codable  {

    /// Plain text message.
    case text(String)

    /// Message containing only attachments.
    case attachments([MessageAttachment])

    /// Message containing only an interactive keyboard.
    ///
    /// Typically used for bot-driven UI (quick replies, menus).
    case keyboard(ChatKeyboard)

    /// Message with combined content.
    ///
    /// Supports:
    /// - text + attachments
    /// - text + keyboard
    /// - attachments + keyboard
    /// - text + attachments + keyboard
    case composite(Composite)

    /// Contact information shared in a message.
    case contact(Contact)

    /// Geographic location shared in a message.
    case location(Location)

    /// System message generated by backend or client logic.
    ///
    /// Examples:
    /// - user joined/left
    /// - status updates
//    case system(System)

    /// Combined message payload.
    public struct Composite: Hashable, Codable {

        /// Optional text content.
        public let text: String?

        /// Attachments included in the message.
        public let attachments: [MessageAttachment]

        /// Optional interactive keyboard.
        ///
        /// Usually provided by the server.
        public let keyboard: ChatKeyboard?
    }

    /// Contact payload.
    public struct Contact: Hashable, Codable {
        public let name: String
        public let phone: String?
        public let email: String?
        public init(name: String, phone: String? = nil, email: String? = nil) {
            self.name = name
            self.phone = phone
            self.email = email
        }
    }

    /// Location payload.
    public struct Location: Hashable, Codable {
        public let name: String
        public let address: String
        public let latitude: Double
        public let longitude: Double
        public init(
            name: String,
            address: String,
            latitude: Double,
            longitude: Double
        ) {
            self.name = name
            self.address = address
            self.latitude = latitude
            self.longitude = longitude
        }
    }

//    /// System payload.
//    public struct System: Hashable, Codable {
//
//        /// System event type (backend-defined).
//        public let type: String
//
//        /// Human-readable description.
//        public let text: String
//    }
}


public extension MessageContent {
    var textValue: String? {
        switch self {

        case .text(let text):
            return text

        case .composite(let composite):
            return composite.text

        default:
            return nil
        }
    }

    var attachmentsValue: [MessageAttachment] {
        switch self {
        case .attachments(let items):
            return items

        case .composite(let composite):
            return composite.attachments

        default:
            return []
        }
    }
}


/// Represents message content that can be sent from the client.
///
/// This is a restricted subset of `MessageContent`.
/// The server may transform or enrich the message after it is sent.
public enum SendContent {

    /// Plain text message.
    case text(String)

    /// Contact sharing message.
    case contact(Contact)

    /// Location sharing message.
    case location(Location)
    
    /// Message containing only attachments.
    case attachments([SendAttachment])

    /// Message with combined content (text + attachments).
    case composite(Composite)
    

    public struct Contact {
        public let name: String
        public let phone: String?
        public let email: String?
        public init(name: String, phone: String? = nil, email: String? = nil) {
            self.name = name
            self.phone = phone
            self.email = email
        }
    }
    

    public struct Location {
        public let name: String
        public let address: String
        public let latitude: Double
        public let longitude: Double
        public init(
            name: String,
            address: String,
            latitude: Double,
            longitude: Double
        ) {
            self.name = name
            self.address = address
            self.latitude = latitude
            self.longitude = longitude
        }
    }
    

    public struct Composite {
        public let text: String
        public let attachments: [SendAttachment]
        public init(text: String, attachments: [SendAttachment] = []) {
            self.text = text
            self.attachments = attachments
        }
    }
}


/// Convenience factory methods for building `SendContent`.
///
/// These helpers provide a clean and concise API, hiding internal models
/// and improving readability at call sites.
public extension SendContent {

    /// Creates a message with text and optional attachments.
    static func composite(
        text: String,
        attachments: [SendAttachment] = []
    ) -> SendContent {
        .composite(.init(text: text, attachments: attachments))
    }

    /// Creates a contact sharing message.
    static func contact(
        name: String,
        phone: String? = nil,
        email: String? = nil
    ) -> SendContent {
        .contact(.init(name: name, phone: phone, email: email))
    }

    /// Creates a location sharing message.
    static func location(
        name: String,
        address: String,
        latitude: Double,
        longitude: Double
    ) -> SendContent {
        .location(.init(
            name: name,
            address: address,
            latitude: latitude,
            longitude: longitude
        ))
    }
}


/// Represents an attachment that can be sent in an outgoing message.
///
/// Attachments are references to already available content,
/// either stored on remote storage or accessible via a public URL.
public enum SendAttachment: Sendable {

    /// A reference to a file that was previously uploaded to remote storage.
    ///
    /// - Parameter: file identifier on the server.
    case file(String)

    /// A reference to an external file accessible via URL.
    ///
    /// - Parameters:
    ///   - url: Direct link to the file.
    ///   - fileName: Original file name including extension.
    case url(URL, String)
}
